#!/bin/sh
#
# env  
#
# LDAP_DOMAIN			ldap domain
# LDAP_ADMIN_PWD		ldap admin passwd
# LDAP_ORGANISATION		orignation
######################################################################
# 

getBaseDn () {
  IFS="."
  export IFS

  domain=$1
  init=1

  for s in $domain; do
    dc="dc=$s"
    if [ "$init" -eq 1 ]; then
      baseDn=$dc
      init=0
    else
      baseDn="$baseDn,$dc"
    fi
  done
  IFS=" "
}

usage () {
  echo "delete user -name username"
  exit 1
}

#######################################################################
# デフォルトを設定する
LDAP_ADD_NAME=

#######################################################################
# 引数を変換する
# -name
for OPT in $*
do
  case $OPT in
    '-name' )
      LDAP_ADD_NAME=${2}
      shift 2
      ;;
  esac
done

getBaseDn ${LDAP_DOMAIN}
LDAP_BASE_DN=$baseDn
LDAP_ADMIN="cn=admin,$baseDn"

ldapdelete -x -w ${LDAP_ADMIN_PWD} -D ${LDAP_ADMIN} "uid=${LDAP_ADD_NAME},ou=People,${LDAP_BASE_DN}"
