#!/bin/sh
#
# env  
#
# LDAP_DOMAIN			ldap domain
# LDAP_ADMIN_PWD		ldap admin passwd
# LDAP_ORGANISATION		orignation
######################################################################
# 

getBaseDn () {
  IFS="."
  export IFS

  domain=$1
  init=1

  for s in $domain; do
    dc="dc=$s"
    if [ "$init" -eq 1 ]; then
      baseDn=$dc
      init=0
    else
      baseDn="$baseDn,$dc"
    fi
  done
  IFS=" "
}

usage () {
  echo "show groups"
  exit 1
}

getBaseDn ${LDAP_DOMAIN}
LDAP_BASE_DN=$baseDn
ldapsearch -x -b "ou=Groups,${LDAP_BASE_DN}" '(cn=*)' cn | grep ^cn | cut -d ' ' -f 2
