#!/bin/bash
#
# env  
#
# LDAP_DOMAIN			ldap domain
# LDAP_ADMIN_PWD		ldap admin passwd
# LDAP_ORGANISATION		orignation
######################################################################
# 

getBaseDn () {
  IFS="."
  export IFS

  domain=$1
  init=1

  for s in $domain; do
    dc="dc=$s"
    if [ "$init" -eq 1 ]; then
      baseDn=$dc
      init=0
    else
      baseDn="$baseDn,$dc"
    fi
  done
  IFS=" "
}

usage () {
  echo "show users -group groupname"
  echo "    -group groupname          find group"
  exit 1
}

#######################################################################
# デフォルトを設定する
LDAP_GROUP_NAME=

#######################################################################
# 引数を変換する

# 
getBaseDn ${LDAP_DOMAIN}
LDAP_BASE_DN=$baseDn
LDAP_ADMIN="cn=admin,$baseDn"

for OPT in $*
do
  case $OPT in
    '-group' )
      LDAP_GROUP_NAME=${2}
      shift 2

      # gidを変換する
      LDAP_GROUP_ID=`ldapsearch -x -w ${LDAP_ADMIN_PWD} -D ${LDAP_ADMIN} -b ${LDAP_BASE_DN} "cn=${LDAP_GROUP_NAME}" | \
                     grep -w "^gidNumber:" | cut -d":" -f 2 | cut -d" " -f 2`
      
      if [ -z "$LDAP_GROUP_ID" ]; then
          usage
          exit
      fi
      ;;
  esac
done


######################################################################

if [ "${LDAP_GROUP_NAME}" == "" ]; then
  ldapsearch -x -b "ou=People,${LDAP_BASE_DN}" '(uid=*)' uid | grep ^uid | cut -d ' ' -f 2
else
  ldapsearch -x -b "ou=People,${LDAP_BASE_DN}"  -s sub gidNumber=${LDAP_GROUP_ID} | grep -w "^uid:" | cut -d ' ' -f 2
fi
