#!/bin/sh
#
# env  
#
# LDAP_DOMAIN			ldap domain
# LDAP_ADMIN_PWD		ldap admin passwd
# LDAP_ORGANISATION		orignation
######################################################################
# 

getBaseDn () {
  IFS="."
  export IFS

  domain=$1
  init=1

  for s in $domain; do
    dc="dc=$s"
    if [ "$init" -eq 1 ]; then
      baseDn=$dc
      init=0
    else
      baseDn="$baseDn,$dc"
    fi
  done
  IFS=" "
}

usage () {
  echo "set passwd -name username -passwd passwd"
  echo "    -name username            "
  echo "    -passwd passwd            "
  exit 1
}

#######################################################################
# デフォルトを設定する
LDAP_ADD_NAME=
LDAP_ADD_PASSWD=

#######################################################################
# 引数を変換する
# -name
# -passwd
for OPT in $*
do
  case $OPT in
    '-name' )
      LDAP_ADD_NAME=${2}
      shift 2
      ;;
    '-passwd' )
      LDAP_ADD_PASSWD=${2}
      shift 2
      ;;
  esac
done

# 必須オプションのチェック
if [ -z "$LDAP_ADD_NAME" ]; then
    usage
    exit
fi
if [ -z "$LDAP_ADD_PASSWD" ]; then
    usage
    exit
fi

getBaseDn ${LDAP_DOMAIN}
LDAP_BASE_DN=$baseDn
LDAP_ADMIN="cn=admin,$baseDn"

ldappasswd -w ${LDAP_ADMIN_PWD} -D ${LDAP_ADMIN} -s ${LDAP_ADD_PASSWD} "uid=${LDAP_ADD_NAME},ou=People,${LDAP_BASE_DN}"
